#!/bin/bash

echo "🔍 检查Supabase数据库表状态"
echo "=============================="
echo "连接字符串: postgresql://postgres:****@db.ywkzdwpgxqslhmamsoav.supabase.co:5432/postgres"
echo ""
echo "预期表 (6个):"
echo "1. Account       (NextAuth)"
echo "2. Session       (NextAuth)"
echo "3. VerificationToken (NextAuth)"
echo "4. User          (应用用户)"
echo "5. Usage         (使用记录)"
echo "6. Payment       (支付记录)"
echo ""
echo "检查方法:"
echo "1. 访问 Supabase Dashboard: https://supabase.com/dashboard/project/ywkzdwpgxqslhmamsoav"
echo "2. 进入 Table Editor"
echo "3. 查看左侧表列表"
echo ""
echo "如果表不全，运行:"
echo "npx prisma db push --accept-data-loss"
echo ""
echo "然后测试注册:"
echo "https://ai-content-distributor-production.vercel.app/auth/signup"
echo ""
echo "当前时间: $(date)"