#!/bin/bash

echo "🚀 创建全新干净仓库方案"
echo "======================"

# 创建临时目录
TEMP_DIR="/tmp/ai-content-distributor-clean-$(date +%s)"
echo "创建临时目录: $TEMP_DIR"
mkdir -p "$TEMP_DIR"

# 复制项目文件（排除.git和历史）
echo "复制项目文件..."
rsync -av --progress \
  --exclude='.git' \
  --exclude='.next' \
  --exclude='node_modules' \
  --exclude='*.db' \
  --exclude='*.db-journal' \
  --exclude='*.log' \
  /Users/joker/.openclaw/workspace/ai-content-distributor/ "$TEMP_DIR/"

# 进入临时目录
cd "$TEMP_DIR"

# 创建全新的.gitignore
cat > .gitignore << 'EOF'
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js
.yarn/install-state.gz

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local
.env.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts

# Prisma
prisma/dev.db
prisma/dev.db-journal

# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# next.js build output
.next

# Local development files
*.local

# Database files
*.db
*.db-journal

# Temporary files
*.tmp
*.temp

# Log files
*.log
logs/

# IDE files
.vscode/
.idea/
*.swp
*.swo

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
EOF

# 初始化Git
echo "初始化Git仓库..."
git init
git add .
git commit -m "Initial commit: AI Content Distributor - Clean version without any hardcoded secrets"

echo ""
echo "🎉 全新干净仓库创建完成！"
echo ""
echo "📁 目录: $TEMP_DIR"
echo ""
echo "🚀 下一步操作:"
echo ""
echo "1. 在GitHub创建新仓库:"
echo "   访问: https://github.com/new"
echo "   名称: ai-content-distributor-v2 或 ai-content-distributor-clean"
echo ""
echo "2. 推送干净代码:"
echo "   cd $TEMP_DIR"
echo "   git remote add origin https://github.com/YOUR_USERNAME/REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Vercel部署:"
echo "   访问: https://vercel.com/new"
echo "   导入新仓库"
echo ""
echo "💡 优势:"
echo "- 无历史提交问题"
echo "- 完全干净的代码库"
echo "- 避免GitHub Secret Scanning阻止"
echo "- 可以立即部署"
echo ""
echo "📋 已包含的文件:"
echo "- 完整Next.js应用代码"
- 所有组件和API
- 数据库配置
- 部署脚本
- 环境变量模板
echo ""
echo "🔐 安全状态:"
echo "✅ 无硬编码API密钥"
echo "✅ 所有密钥通过环境变量配置"
echo "✅ 可以通过GitHub安全检查"