#!/bin/bash

echo "🎯 AI Content Distributor - 最简单部署指南"
echo "========================================"
echo ""
echo "只需3步，15分钟完成部署！"
echo ""

echo "📝 第一步: 创建GitHub仓库 (2分钟)"
echo "--------------------------------"
echo "1. 打开浏览器，访问: https://github.com/new"
echo "2. 填写信息:"
echo "   - Repository name: ai-content-distributor"
echo "   - Description: AI content distribution platform"
echo "   - 选择: Public (推荐) 或 Private"
echo "   - 不要勾选 'Initialize with README'"
echo "3. 点击: Create repository"
echo "4. 复制仓库URL (如: https://github.com/YOUR_USERNAME/ai-content-distributor)"
echo ""
read -p "按Enter继续查看第二步..." 

echo ""
echo "🚀 第二步: 推送代码到GitHub (1分钟)"
echo "----------------------------------"
echo "在终端执行以下命令:"
echo ""
echo "cd /Users/joker/.openclaw/workspace/ai-content-distributor"
echo "git remote add origin https://github.com/YOUR_USERNAME/ai-content-distributor.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "将 YOUR_USERNAME 替换为你的GitHub用户名"
echo ""
read -p "按Enter继续查看第三步..." 

echo ""
echo "🌐 第三步: Vercel一键部署 (3分钟)"
echo "--------------------------------"
echo "1. 访问: https://vercel.com/new"
echo "2. 点击: 'Import Git Repository'"
echo "3. 选择: 你的 'ai-content-distributor' 仓库"
echo "4. 点击: 'Import'"
echo "5. 等待部署完成 (约2分钟)"
echo ""
echo "🎉 完成！你的应用将运行在: https://ai-content-distributor.vercel.app"
echo ""
read -p "按Enter查看环境变量配置..." 

echo ""
echo "🔧 第四步: 配置环境变量 (5分钟)"
echo "-----------------------------"
echo "部署完成后，在Vercel中添加以下变量:"
echo ""
echo "1. NEXTAUTH_SECRET"
echo "   生成命令: openssl rand -base64 32"
echo "   示例: $(openssl rand -base64 32 2>/dev/null || echo 'your-secret-here')"
echo ""
echo "2. NEXTAUTH_URL"
echo "   值: https://ai-content-distributor.vercel.app"
echo ""
echo "3. DATABASE_URL"
echo "   使用Vercel Postgres: 在Vercel Dashboard → Storage → Postgres创建"
echo ""
echo "4. OPENAI_API_KEY"
echo "   值: YOUR_OPENAI_API_KEY"
echo ""
echo "5. OPENAI_BASE_URL"
echo "   值: https://poloai.top/v1"
echo ""
echo "6. STRIPE_SECRET_KEY"
echo "   值: YOUR_STRIPE_TEST_SECRET_KEY"
echo ""
echo "7. STRIPE_WEBHOOK_SECRET"
echo "   值: whsec_test"
echo ""
echo "8. NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "   值: YOUR_STRIPE_TEST_PUBLISHABLE_KEY"
echo ""
read -p "按Enter查看测试步骤..." 

echo ""
echo "✅ 第五步: 测试应用 (5分钟)"
echo "--------------------------"
echo "1. 访问: https://ai-content-distributor.vercel.app"
echo "2. 注册账号: 点击 'Sign Up Free'"
echo "3. 登录: 使用注册的邮箱密码"
echo "4. 生成内容: 输入文本，选择平台，点击生成"
echo "5. 测试支付: 访问 /pricing，使用测试卡号 4242 4242 4242 4242"
echo ""
echo "🎊 恭喜！你的AI赚钱系统已上线！"
echo ""
echo "💡 提示:"
echo "- 查看 DEPLOY_NOW.md 获取详细指南"
echo "- 使用 check-deployment.sh 检查问题"
echo "- 收入将进入你的Stripe账户"
echo ""
echo "🚀 现在开始执行第一步吧！"